// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: rpc/protos/spdk.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Spdk_GetSpdkVersion_FullMethodName = "/Spdk/GetSpdkVersion"
)

// SpdkClient is the client API for Spdk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpdkClient interface {
	GetSpdkVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SpdkVersion, error)
}

type spdkClient struct {
	cc grpc.ClientConnInterface
}

func NewSpdkClient(cc grpc.ClientConnInterface) SpdkClient {
	return &spdkClient{cc}
}

func (c *spdkClient) GetSpdkVersion(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SpdkVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpdkVersion)
	err := c.cc.Invoke(ctx, Spdk_GetSpdkVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpdkServer is the server API for Spdk service.
// All implementations must embed UnimplementedSpdkServer
// for forward compatibility.
type SpdkServer interface {
	GetSpdkVersion(context.Context, *emptypb.Empty) (*SpdkVersion, error)
	mustEmbedUnimplementedSpdkServer()
}

// UnimplementedSpdkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpdkServer struct{}

func (UnimplementedSpdkServer) GetSpdkVersion(context.Context, *emptypb.Empty) (*SpdkVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpdkVersion not implemented")
}
func (UnimplementedSpdkServer) mustEmbedUnimplementedSpdkServer() {}
func (UnimplementedSpdkServer) testEmbeddedByValue()              {}

// UnsafeSpdkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpdkServer will
// result in compilation errors.
type UnsafeSpdkServer interface {
	mustEmbedUnimplementedSpdkServer()
}

func RegisterSpdkServer(s grpc.ServiceRegistrar, srv SpdkServer) {
	// If the following call pancis, it indicates UnimplementedSpdkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Spdk_ServiceDesc, srv)
}

func _Spdk_GetSpdkVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpdkServer).GetSpdkVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Spdk_GetSpdkVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpdkServer).GetSpdkVersion(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Spdk_ServiceDesc is the grpc.ServiceDesc for Spdk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Spdk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Spdk",
	HandlerType: (*SpdkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSpdkVersion",
			Handler:    _Spdk_GetSpdkVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/protos/spdk.proto",
}
